apiVersion: 1

datasources:
- name: Loki
  type: loki
  url: http://loki:3100
  isDefault: true
  uid: loki
  jsonData:
    maxLines: 1000
    derivedFields:
    # Field with external link.
    - datasourceUid: Tempo
      matcherRegex: "(?:traceId) (\\w+)"
      name: TraceID
      url: '$${__value.raw}'
- name: Tempo
  type: tempo
  uid: tempo
  # Access mode - proxy (server in the UI) or direct (browser in the UI).
  access: proxy
  url: http://tempo:3200
  jsonData:
    httpMethod: GET
    tracesToLogs:
      datasourceUid: 'loki'
      tags: ['job', 'instance', 'pod', 'namespace']
      mappedTags: [{ key: 'service.name', value: 'service' }]
      mapTagNamesEnabled: false
      spanStartTimeShift: '1h'
      spanEndTimeShift: '1h'
      filterByTraceID: false
      filterBySpanID: false
    search:
      hide: false
    nodeGraph:
      enabled: true
    lokiSearch:
      datasourceUid: 'loki'
    serviceMap:
      datasourceUid: 'prometheus'
- name: Prometheus
  type: prometheus
  url: http://prometheus:9090
  uid: prometheus
